# Introduction
Welcome to the Pandas DataFrame Mutations Lab: Exploring Airbnb Listings!

In this coding lab, you will learn creating new columns, deleting rows ad columns, modifying dataframe structure, add new rows, and use of inplace parameter. We will be working with the Airbnb Listings dataset, which contains information about various Airbnb listings in US States. This dataset will serve as the foundation for our exploration and learning journey.

###Dataset Description:

The Airbnb Listings dataset provides valuable insights into the world of short-term vacation rentals. It includes details such as the listing ID, name, host ID, host name, neighborhood, geographical coordinates, room type, pricing information, minimum nights required, and various other attributes that define each listing. By leveraging this dataset, we can extract meaningful information, uncover patterns, and gain insights into the Airbnb market in US States.

By working through this coding lab, you will develop a solid understanding of pandas and gain hands-on experience in performing data manipulation, analysis, and transformation tasks. These skills will be valuable in various data-driven domains, from business analytics to Data Science.

Now, it's time to roll up your sleeves, fire up your Jupyter notebooks, and let's embark on this exciting journey of exploring the Airbnb Listings dataset using pandas!

## Look at the Dataset

In [2]:
# importing pandas library
import pandas as pd

In [12]:
df = pd.read_csv('/content/AB_US_2023.csv', low_memory=False, parse_dates=['last_review'])
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,city
0,958,"Bright, Modern Garden Unit - 1BR/1BTH",1169,Holly,NaN,Western Addition,37.77028,-122.43317,Entire home/apt,202,2,383,2023-02-19,2.31,1,128,59,San Francisco
1,5858,Creative Sanctuary,8904,Philip And Tania,NaN,Bernal Heights,37.74474,-122.42089,Entire home/apt,235,30,111,2017-08-06,0.66,1,365,0,San Francisco
2,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,21994,Aaron,NaN,Haight Ashbury,37.76555,-122.45213,Private room,56,32,9,2022-10-27,0.09,13,365,1,San Francisco
3,8339,Historic Alamo Square Victorian,24215,Rosy,NaN,Western Addition,37.77564,-122.43642,Entire home/apt,575,9,28,2019-06-28,0.17,2,365,0,San Francisco
4,8739,"Mission Sunshine, with Private Bath",7149,Ivan & Wendy,NaN,Mission,37.76030,-122.42197,Private room,110,1,770,2023-02-25,4.65,2,159,34,San Francisco

In [4]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'city'],
      dtype='object')

In [5]:
df.shape

(232147, 18)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232147 entries, 0 to 232146
Data columns (total 18 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              232147 non-null  int64
 1   name                            232131 non-null  object
 2   host_id                         232147 non-null  int64
 3   host_name                       232134 non-null  object
 4   neighbourhood_group             96500 non-null   object
 5   neighbourhood                   232147 non-null  object
 6   latitude                        232147 non-null  float64
 7   longitude                       232147 non-null  float64
 8   room_type                       232147 non-null  object
 9   price                           232147 non-null  int64
 10  minimum_nights                  232147 non-null  int64
 11  number_of_reviews               232147 non-null  int64
 12  last_review                     183062 non-null  datetime64[ns]
 13  reviews_per_month               183062 non-null  float64
 14  calculated_host_listings_count  232147 non-null  int64
 15  availability_365                232147 non-null  int64
 16  number_of_reviews_ltm           232147 non-null  int64
 17  city                            232147 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(8), object(6)
memory usage: 31.9+ MB

In [7]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm
count,2.321470e+05,2.321470e+05,232147.000000,232147.000000,232147.000000,232147.000000,232147.000000,183062.000000,232147.000000,232147.000000,232147.000000
mean,2.584580e+17,1.582248e+08,36.610585,-98.301436,259.468001,13.495867,40.915230,1.638348,29.879055,180.985686,11.689701
std,3.465985e+17,1.587164e+08,5.126523,19.706929,1024.645918,27.920631,80.649152,1.910812,106.013665,134.715299,20.599954
min,6.000000e+00,2.300000e+01,25.957323,-123.089130,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000,0.000000
25%,2.638896e+07,2.299242e+07,33.976225,-118.315111,91.000000,2.000000,1.000000,0.310000,1.000000,52.000000,0.000000
50%,4.896307e+07,1.005783e+08,36.190556,-97.727670,149.000000,3.000000,9.000000,1.000000,2.000000,175.000000,3.000000
75%,6.633014e+17,2.686930e+08,40.717440,-77.026222,250.000000,30.000000,43.000000,2.420000,10.000000,321.000000,16.000000
max,8.581014e+17,5.069384e+08,47.734010,-70.996000,100000.000000,1250.000000,3091.000000,101.420000,1003.000000,365.000000,1314.000000

In [8]:
df.isnull().sum()

id                                     0
name                                  16
host_id                                0
host_name                             13
neighbourhood_group               135647
neighbourhood                          0
latitude                               0
longitude                              0
room_type                              0
price                                  0
minimum_nights                         0
number_of_reviews                      0
last_review                        49085
reviews_per_month                  49085
calculated_host_listings_count         0
availability_365                       0
number_of_reviews_ltm                  0
city                                   0
dtype: int64

# Activities:

## 1. Create a New Column price_per_night

Create a new column called price_per_night that calculates the price per night for each Airbnb listing.

In [13]:
# try your code here
df['price_per_night'] = df['price'] / df['minimum_nights']
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,city,price_per_night
0,958,"Bright, Modern Garden Unit - 1BR/1BTH",1169,Holly,NaN,Western Addition,37.770280,-122.433170,Entire home/apt,202,2,383,2023-02-19,2.31,1,128,59,San Francisco,101.000000
1,5858,Creative Sanctuary,8904,Philip And Tania,NaN,Bernal Heights,37.744740,-122.420890,Entire home/apt,235,30,111,2017-08-06,0.66,1,365,0,San Francisco,7.833333
2,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,21994,Aaron,NaN,Haight Ashbury,37.765550,-122.452130,Private room,56,32,9,2022-10-27,0.09,13,365,1,San Francisco,1.750000
3,8339,Historic Alamo Square Victorian,24215,Rosy,NaN,Western Addition,37.775640,-122.436420,Entire home/apt,575,9,28,2019-06-28,0.17,2,365,0,San Francisco,63.888889
4,8739,"Mission Sunshine, with Private Bath",7149,Ivan & Wendy,NaN,Mission,37.760300,-122.421970,Private room,110,1,770,2023-02-25,4.65,2,159,34,San Francisco,110.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232142,849230448624862502,Private Half Moon Bay Oasis By Pillar Point Be...,29395385,Khalid,NaN,Unincorporated Areas,37.506164,-122.476188,Entire home/apt,389,2,0,NaT,NaN,1,365,0,San Mateo County,194.500000
232143,850805127216414630,Home near SFO,440957696,Christina,NaN,San Bruno,37.623630,-122.426570,Entire home/apt,158,1,0,NaT,NaN,1,364,0,San Mateo County,158.000000
232144,851562104616413652,Modern New Private Studio in SFO,41574587,Vality,NaN,South San Francisco,37.655661,-122.413130,Entire home/apt,97,1,0,NaT,NaN,32,359,0,San Mateo County,97.000000
232145,851792795339759410,Lux Bedroom with a Shared Bath near SFO,73133543,Stephannie,NaN,South San Francisco,37.644792,-122.454213,Private room,62,2,0,NaT,NaN,3,67,0,San Mateo County,31.000000
232146,851801296770555568,Lux Bedroom with Private Bath near SFO,73133543,Stephannie,NaN,South San Francisco,37.642655,-122.452391,Private room,85,2,0,NaT,NaN,3,69,0,San Mateo County,42.500000

## 2. Delete all rows where the price is greater than $500

In [14]:
# try your code here
df = df.query('price <= 500')
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,city,price_per_night
0,958,"Bright, Modern Garden Unit - 1BR/1BTH",1169,Holly,NaN,Western Addition,37.770280,-122.433170,Entire home/apt,202,2,383,2023-02-19,2.31,1,128,59,San Francisco,101.000000
1,5858,Creative Sanctuary,8904,Philip And Tania,NaN,Bernal Heights,37.744740,-122.420890,Entire home/apt,235,30,111,2017-08-06,0.66,1,365,0,San Francisco,7.833333
2,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,21994,Aaron,NaN,Haight Ashbury,37.765550,-122.452130,Private room,56,32,9,2022-10-27,0.09,13,365,1,San Francisco,1.750000
4,8739,"Mission Sunshine, with Private Bath",7149,Ivan & Wendy,NaN,Mission,37.760300,-122.421970,Private room,110,1,770,2023-02-25,4.65,2,159,34,San Francisco,110.000000
5,10537,Elegant & Cozy w/City views. Private room: Purple,36752,Teresa,NaN,Bayview,37.717500,-122.396980,Private room,95,1,19,2023-01-28,0.12,2,365,1,San Francisco,95.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232142,849230448624862502,Private Half Moon Bay Oasis By Pillar Point Be...,29395385,Khalid,NaN,Unincorporated Areas,37.506164,-122.476188,Entire home/apt,389,2,0,NaT,NaN,1,365,0,San Mateo County,194.500000
232143,850805127216414630,Home near SFO,440957696,Christina,NaN,San Bruno,37.623630,-122.426570,Entire home/apt,158,1,0,NaT,NaN,1,364,0,San Mateo County,158.000000
232144,851562104616413652,Modern New Private Studio in SFO,41574587,Vality,NaN,South San Francisco,37.655661,-122.413130,Entire home/apt,97,1,0,NaT,NaN,32,359,0,San Mateo County,97.000000
232145,851792795339759410,Lux Bedroom with a Shared Bath near SFO,73133543,Stephannie,NaN,South San Francisco,37.644792,-122.454213,Private room,62,2,0,NaT,NaN,3,67,0,San Mateo County,31.000000
232146,851801296770555568,Lux Bedroom with Private Bath near SFO,73133543,Stephannie,NaN,South San Francisco,37.642655,-122.452391,Private room,85,2,0,NaT,NaN,3,69,0,San Mateo County,42.500000

## 3. Delete the host_name and neighbourhood_group columns from the DataFrame df

Modify the original DataFrame df.

In [15]:
# try your code here
df.drop(['host_name', 'neighbourhood_group'], axis = 1, inplace = True)

<ipython-input-15-494022141ee6>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(['host_name', 'neighbourhood_group'], axis = 1, inplace = True)

In [17]:
df.columns

Index(['id', 'name', 'host_id', 'neighbourhood', 'latitude', 'longitude',
       'room_type', 'price', 'minimum_nights', 'number_of_reviews',
       'last_review', 'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'city', 'price_per_night'],
      dtype='object')

## 4. Rename the column number_of_reviews to reviews_count

In [18]:
# try your code here
df.rename(columns= {'number_of_reviews':'reviews_count'}, inplace=True)
df

<ipython-input-18-1cccc148f6e3>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns= {'number_of_reviews':'reviews_count'}, inplace=True)

,id,name,host_id,neighbourhood,latitude,longitude,room_type,price,minimum_nights,reviews_count,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,city,price_per_night
0,958,"Bright, Modern Garden Unit - 1BR/1BTH",1169,Western Addition,37.770280,-122.433170,Entire home/apt,202,2,383,2023-02-19,2.31,1,128,59,San Francisco,101.000000
1,5858,Creative Sanctuary,8904,Bernal Heights,37.744740,-122.420890,Entire home/apt,235,30,111,2017-08-06,0.66,1,365,0,San Francisco,7.833333
2,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,21994,Haight Ashbury,37.765550,-122.452130,Private room,56,32,9,2022-10-27,0.09,13,365,1,San Francisco,1.750000
4,8739,"Mission Sunshine, with Private Bath",7149,Mission,37.760300,-122.421970,Private room,110,1,770,2023-02-25,4.65,2,159,34,San Francisco,110.000000
5,10537,Elegant & Cozy w/City views. Private room: Purple,36752,Bayview,37.717500,-122.396980,Private room,95,1,19,2023-01-28,0.12,2,365,1,San Francisco,95.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232142,849230448624862502,Private Half Moon Bay Oasis By Pillar Point Be...,29395385,Unincorporated Areas,37.506164,-122.476188,Entire home/apt,389,2,0,NaT,NaN,1,365,0,San Mateo County,194.500000
232143,850805127216414630,Home near SFO,440957696,San Bruno,37.623630,-122.426570,Entire home/apt,158,1,0,NaT,NaN,1,364,0,San Mateo County,158.000000
232144,851562104616413652,Modern New Private Studio in SFO,41574587,South San Francisco,37.655661,-122.413130,Entire home/apt,97,1,0,NaT,NaN,32,359,0,San Mateo County,97.000000
232145,851792795339759410,Lux Bedroom with a Shared Bath near SFO,73133543,South San Francisco,37.644792,-122.454213,Private room,62,2,0,NaT,NaN,3,67,0,San Mateo County,31.000000
232146,851801296770555568,Lux Bedroom with Private Bath near SFO,73133543,South San Francisco,37.642655,-122.452391,Private room,85,2,0,NaT,NaN,3,69,0,San Mateo County,42.500000

## 5. Convert the price column from integer to float data type

In [19]:
# try your code here
df['price'] = df['price'].astype(float)

<ipython-input-19-66918bd7cbea>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'] = df['price'].astype(float)

In [22]:
df['price'].info()

<class 'pandas.core.series.Series'>
Int64Index: 214407 entries, 0 to 232146
Series name: price
Non-Null Count   Dtype
--------------   -----
214407 non-null  float64
dtypes: float64(1)
memory usage: 3.3 MB

## 6. Replace all occurrences of Private room in the room_type column with Private

In [23]:
# try your code here
df.loc[df['room_type'] == 'Private room', 'room_type'] = 'Private'

In [24]:
df['room_type'].value_counts()

Entire home/apt    153740
Private             57758
Shared room          2229
Hotel room            680
Name: room_type, dtype: int64

##7. Add new row with the given details

Add a new row to the DataFrame df at the end with the following details:

new_row_data = {'id': 851792795339743534, 'name': 'Tony Stark Apartment', 'host_id': 67890, 'room_type': 'Entire home/apt',
                'price': 150, 'minimum_nights': 3, 'reviews_count': 10}

In [25]:
new_row_data = {'id': 851792795339743534, 'name': 'Tony Stark Apartment', 'host_id': 67890, 'room_type': 'Entire home/apt',
                'price': 150, 'minimum_nights': 3, 'reviews_count': 10}

In [26]:
# try your code here
new_row = pd.DataFrame(new_row_data, index=[len(df)])
df = pd.concat([df, new_row])
df.tail()

,id,name,host_id,neighbourhood,latitude,longitude,room_type,price,minimum_nights,reviews_count,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,city,price_per_night
232143,850805127216414630,Home near SFO,440957696,San Bruno,37.623630,-122.426570,Entire home/apt,158.0,1,0,NaT,NaN,1.0,364.0,0.0,San Mateo County,158.0
232144,851562104616413652,Modern New Private Studio in SFO,41574587,South San Francisco,37.655661,-122.413130,Entire home/apt,97.0,1,0,NaT,NaN,32.0,359.0,0.0,San Mateo County,97.0
232145,851792795339759410,Lux Bedroom with a Shared Bath near SFO,73133543,South San Francisco,37.644792,-122.454213,Private,62.0,2,0,NaT,NaN,3.0,67.0,0.0,San Mateo County,31.0
232146,851801296770555568,Lux Bedroom with Private Bath near SFO,73133543,South San Francisco,37.642655,-122.452391,Private,85.0,2,0,NaT,NaN,3.0,69.0,0.0,San Mateo County,42.5
214407,851792795339743534,Tony Stark Apartment,67890,NaN,NaN,NaN,Entire home/apt,150.0,3,10,NaT,NaN,NaN,NaN,NaN,NaN,NaN

## 8. Remove the availability_365 column from the DataFrame without creating a new DataFrame

In [27]:
# try your code here
df.drop(columns = 'availability_365', axis =1, inplace=True)
df

,id,name,host_id,neighbourhood,latitude,longitude,room_type,price,minimum_nights,reviews_count,last_review,reviews_per_month,calculated_host_listings_count,number_of_reviews_ltm,city,price_per_night
0,958,"Bright, Modern Garden Unit - 1BR/1BTH",1169,Western Addition,37.770280,-122.433170,Entire home/apt,202.0,2,383,2023-02-19,2.31,1.0,59.0,San Francisco,101.000000
1,5858,Creative Sanctuary,8904,Bernal Heights,37.744740,-122.420890,Entire home/apt,235.0,30,111,2017-08-06,0.66,1.0,0.0,San Francisco,7.833333
2,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,21994,Haight Ashbury,37.765550,-122.452130,Private,56.0,32,9,2022-10-27,0.09,13.0,1.0,San Francisco,1.750000
4,8739,"Mission Sunshine, with Private Bath",7149,Mission,37.760300,-122.421970,Private,110.0,1,770,2023-02-25,4.65,2.0,34.0,San Francisco,110.000000
5,10537,Elegant & Cozy w/City views. Private room: Purple,36752,Bayview,37.717500,-122.396980,Private,95.0,1,19,2023-01-28,0.12,2.0,1.0,San Francisco,95.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232143,850805127216414630,Home near SFO,440957696,San Bruno,37.623630,-122.426570,Entire home/apt,158.0,1,0,NaT,NaN,1.0,0.0,San Mateo County,158.000000
232144,851562104616413652,Modern New Private Studio in SFO,41574587,South San Francisco,37.655661,-122.413130,Entire home/apt,97.0,1,0,NaT,NaN,32.0,0.0,San Mateo County,97.000000
232145,851792795339759410,Lux Bedroom with a Shared Bath near SFO,73133543,South San Francisco,37.644792,-122.454213,Private,62.0,2,0,NaT,NaN,3.0,0.0,San Mateo County,31.000000
232146,851801296770555568,Lux Bedroom with Private Bath near SFO,73133543,South San Francisco,37.642655,-122.452391,Private,85.0,2,0,NaT,NaN,3.0,0.0,San Mateo County,42.500000
214407,851792795339743534,Tony Stark Apartment,67890,NaN,NaN,NaN,Entire home/apt,150.0,3,10,NaT,NaN,NaN,NaN,NaN,NaN

## 9. Sort the DataFrame by the price column in descending order

Sort the DataFrame df by the price column in descending order and assign the result to sorted_df.

In [28]:
# try your code here
sorted_df = df.sort_values(by='price', ascending = False)
sorted_df

,id,name,host_id,neighbourhood,latitude,longitude,room_type,price,minimum_nights,reviews_count,last_review,reviews_per_month,calculated_host_listings_count,number_of_reviews_ltm,city,price_per_night
165832,11678958,Apartment For Rent,62031659,78704,30.25518,-97.770590,Entire home/apt,500.0,1,0,NaT,NaN,1.0,0.0,Austin,500.000000
37882,21850379,2 Bed 2 Bath in Heart of Westwood,29591316,Westwood,34.06068,-118.442210,Entire home/apt,500.0,30,3,2019-12-15,0.05,9.0,0.0,Los Angeles,16.666667
135561,34285958,GreatLocation 1BR San Diego Pulse Suite+Amenities,236664052,Cortez Hill,32.71966,-117.156950,Entire home/apt,500.0,2,0,NaT,NaN,1.0,0.0,San Diego,250.000000
89279,45992659,Rego park / corona modern apartment,1761578,Corona,40.73554,-73.861450,Entire home/apt,500.0,2,5,2022-07-28,0.25,3.0,3.0,New York City,250.000000
55390,742067782332636396,Near the beach and central located,100428075,Long Beach,33.77998,-118.101030,Entire home/apt,500.0,1,2,2023-01-15,0.57,43.0,2.0,Los Angeles,500.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20707,42535097,The Drifter / 21+ / Boutique Hotel,315008938,Mid-City,29.96600,-90.100230,Hotel room,0.0,1,0,NaT,NaN,1.0,0.0,New Orleans,0.000000
226608,42065556,Inn @ St. Botolph,107268789,Back Bay,42.34503,-71.080850,Hotel room,0.0,91,20,2022-10-02,0.74,1.0,2.0,Boston,0.000000
20722,42875637,Federal City Inn & Suites,266877580,U.S. Naval Base,29.94758,-90.032720,Hotel room,0.0,1,3,2021-03-21,0.09,1.0,0.0,New Orleans,0.000000
5073,52498132,"Bedroom, bath and garden",2577011,Parkside,37.73933,-122.477920,Private,0.0,1,3,2021-11-28,0.18,2.0,0.0,San Francisco,0.000000
50288,46396590,Shore Hotel,375439118,Santa Monica,34.01202,-118.496275,Hotel room,0.0,1,3,2022-08-18,0.15,1.0,2.0,Los Angeles,0.000000

## 10. Convert all prices from US dollars to euros

Create a new column price_eur in the DataFrame df that contains the prices in euros. The conversion rate is 1 US dollar = 0.85 euros.

In [29]:
# try your code here
df['price_eur'] = df['price'] * 0.85
df.columns

Index(['id', 'name', 'host_id', 'neighbourhood', 'latitude', 'longitude',
       'room_type', 'price', 'minimum_nights', 'reviews_count', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'number_of_reviews_ltm', 'city', 'price_per_night', 'price_eur'],
      dtype='object')

## 11. Modify the price_per_night by doubling the rates.

Modify the price_per_night column by doubling the rates. For example, if the price_per_night column contains the value 50, it should be modified to 100.

Modify the original DataFrame df.

In [30]:
# try your code here
df['price_per_night'] = df['price_per_night'] * 2
df['price_per_night']

0         202.000000
1          15.666667
2           3.500000
4         220.000000
5         190.000000
             ...
232143    316.000000
232144    194.000000
232145     62.000000
232146     85.000000
214407           NaN
Name: price_per_night, Length: 214408, dtype: float64

## 12. Create a new column named year that contains the year information from the last_review column

Create a new column year in the DataFrame df that contains the year information from the last_review column. For example, if the last_review column contains the date 2019-05-21, the year column should contain the value 2019. You can use the dt accessor to access the datetime properties of a column. For example, df['last_review'].dt.year returns the year information from the last_review column.

In [31]:
# try your code here
df['year'] = df['last_review'].dt.year
df

,id,name,host_id,neighbourhood,latitude,longitude,room_type,price,minimum_nights,reviews_count,last_review,reviews_per_month,calculated_host_listings_count,number_of_reviews_ltm,city,price_per_night,price_eur,year
0,958,"Bright, Modern Garden Unit - 1BR/1BTH",1169,Western Addition,37.770280,-122.433170,Entire home/apt,202.0,2,383,2023-02-19,2.31,1.0,59.0,San Francisco,202.000000,171.70,2023.0
1,5858,Creative Sanctuary,8904,Bernal Heights,37.744740,-122.420890,Entire home/apt,235.0,30,111,2017-08-06,0.66,1.0,0.0,San Francisco,15.666667,199.75,2017.0
2,8142,Friendly Room Apt. Style -UCSF/USF - San Franc...,21994,Haight Ashbury,37.765550,-122.452130,Private,56.0,32,9,2022-10-27,0.09,13.0,1.0,San Francisco,3.500000,47.60,2022.0
4,8739,"Mission Sunshine, with Private Bath",7149,Mission,37.760300,-122.421970,Private,110.0,1,770,2023-02-25,4.65,2.0,34.0,San Francisco,220.000000,93.50,2023.0
5,10537,Elegant & Cozy w/City views. Private room: Purple,36752,Bayview,37.717500,-122.396980,Private,95.0,1,19,2023-01-28,0.12,2.0,1.0,San Francisco,190.000000,80.75,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232143,850805127216414630,Home near SFO,440957696,San Bruno,37.623630,-122.426570,Entire home/apt,158.0,1,0,NaT,NaN,1.0,0.0,San Mateo County,316.000000,134.30,NaN
232144,851562104616413652,Modern New Private Studio in SFO,41574587,South San Francisco,37.655661,-122.413130,Entire home/apt,97.0,1,0,NaT,NaN,32.0,0.0,San Mateo County,194.000000,82.45,NaN
232145,851792795339759410,Lux Bedroom with a Shared Bath near SFO,73133543,South San Francisco,37.644792,-122.454213,Private,62.0,2,0,NaT,NaN,3.0,0.0,San Mateo County,62.000000,52.70,NaN
232146,851801296770555568,Lux Bedroom with Private Bath near SFO,73133543,South San Francisco,37.642655,-122.452391,Private,85.0,2,0,NaT,NaN,3.0,0.0,San Mateo County,85.000000,72.25,NaN
214407,851792795339743534,Tony Stark Apartment,67890,NaN,NaN,NaN,Entire home/apt,150.0,3,10,NaT,NaN,NaN,NaN,NaN,NaN,127.50,NaN